/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupaRouteImport } from './routes/supa'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTwilioWhatsappV1RouteImport } from './routes/api/twilio/whatsapp/v1'

const SupaRoute = SupaRouteImport.update({
  id: '/supa',
  path: '/supa',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioWhatsappV1Route = ApiTwilioWhatsappV1RouteImport.update({
  id: '/api/twilio/whatsapp/v1',
  path: '/api/twilio/whatsapp/v1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supa': typeof SupaRoute
  '/api/twilio/whatsapp/v1': typeof ApiTwilioWhatsappV1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supa': typeof SupaRoute
  '/api/twilio/whatsapp/v1': typeof ApiTwilioWhatsappV1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supa': typeof SupaRoute
  '/api/twilio/whatsapp/v1': typeof ApiTwilioWhatsappV1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/supa' | '/api/twilio/whatsapp/v1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/supa' | '/api/twilio/whatsapp/v1'
  id: '__root__' | '/' | '/about' | '/supa' | '/api/twilio/whatsapp/v1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SupaRoute: typeof SupaRoute
  ApiTwilioWhatsappV1Route: typeof ApiTwilioWhatsappV1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supa': {
      id: '/supa'
      path: '/supa'
      fullPath: '/supa'
      preLoaderRoute: typeof SupaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/whatsapp/v1': {
      id: '/api/twilio/whatsapp/v1'
      path: '/api/twilio/whatsapp/v1'
      fullPath: '/api/twilio/whatsapp/v1'
      preLoaderRoute: typeof ApiTwilioWhatsappV1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SupaRoute: SupaRoute,
  ApiTwilioWhatsappV1Route: ApiTwilioWhatsappV1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
